### ISSUE TITLE
请教一个问题：我看代码里面还是用到了wx.request方法发请求啊，到底是怎么实现突破微信的5个并发请求数限制呢？

### ISSUE THREAD

**Issue by unclechen** [JoeZheng2015/wx-queue-request#2]
rt

**Comment by zhengjunxin** [comment]
使用队列。即超过5个并发数后，后面的请求就不发起了，等前面的请求完成了再继续发起请求，保证同时并发数不超过5个

**Comment by unclechen** [comment]
@zhengjunxin 所以说，其实queue(20)是不可以的，最多只能queue(10)对吧？

**Comment by zhengjunxin** [comment]
@unclechen 是的。除非微信提高并发数的限制，不然设置`queue(20)`没啥意义

**Comment by unclechen** [comment]
@zhengjunxin 明白了，多谢~
