### ISSUE TITLE
邀请你编写 wxPromise

### ISSUE THREAD

**Issue by zisheng-ai** [JoeZheng2015/wx-queue-request#3]
你好，我是 [wxPromise](https://github.com/youngjuning/wxPromise) 的作者，想要把您的这个关于 请求队列的方案引入我的库中，希望能和您合作

**Comment by zhengjunxin** [comment]
@youngjuning  你好，怎么合作呢？

**Comment by zisheng-ai** [comment]
@zhengjunxin 你可以看下我的库的readme，做个了解。我就是想引入请求对列这个功能

**Comment by zisheng-ai** [comment]
https://github.com/youngjuning/wxPromise

**Comment by zisheng-ai** [comment]
微信号 y_m_j_x

**Comment by zhengjunxin** [comment]
如果是引入就直接引入呗，我用的也是MIT协议

**Comment by zisheng-ai** [comment]
ok，引入这个对吧：https://github.com/zhengjunxin/wx-queue-request/blob/master/src/queue.js

**Comment by zhengjunxin** [comment]
是的
